name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload everything in the root directory
          name: github-pages  # Name must match deployment step

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Ensure the artifact name matches
